"""Framework-independent domain model."""

from rebel_dot.domain.errors import (
    AIProviderError,
    EmbeddingProviderError,
    GuardrailRejectedError,
    OptimisticConcurrencyError,
    OutputRejectedError,
    ProviderFailureKind,
)
from rebel_dot.domain.models import (
    AnswerSource,
    AuthSession,
    CollectionStatus,
    EmbeddingJob,
    EmbeddingJobStatus,
    ErrorCode,
    FAQCollection,
    FAQItem,
    GuardrailReason,
    GuardrailResult,
    QuestionAnswer,
    RetrievalCandidate,
    Route,
    RoutingEvidence,
    ScopeDecision,
    ScopeResult,
    WorkflowState,
)

__all__ = [
    "AIProviderError",
    "AnswerSource",
    "AuthSession",
    "CollectionStatus",
    "EmbeddingJob",
    "EmbeddingJobStatus",
    "EmbeddingProviderError",
    "ErrorCode",
    "FAQCollection",
    "FAQItem",
    "GuardrailReason",
    "GuardrailRejectedError",
    "GuardrailResult",
    "OptimisticConcurrencyError",
    "OutputRejectedError",
    "ProviderFailureKind",
    "QuestionAnswer",
    "RoutingEvidence",
    "RetrievalCandidate",
    "Route",
    "ScopeDecision",
    "ScopeResult",
    "WorkflowState",
]
